# Generated by Django 3.1.4 on 2020-12-09 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('company_name', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('company_description', models.TextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('last_date', models.DateField()),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='listings.category')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recruiters.recruiter')),
            ],
        ),
    ]
