# Generated by Django 3.1.4 on 2020-12-09 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201209_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='logo',
            new_name='photo_main',
        ),
    ]
